### ISSUE TITLE
moveToRangeOfNode not working after updating to 0.42.2

### ISSUE THREAD

**Issue by crisward** [ianstormtaylor/slate#2289]
## Current Behaviour (0.42.2)

https://jsfiddle.net/fj9dvhom/2524/
```javascript
   this.editor.change((change)=>{
      var node = change.value.startBlock;
      change.replaceNodeByKey(node.key,insertblock).moveToRangeOfNode(insertblock)
    })
```
`moveToRangeOfNode` causes a `node.getFirstText is not a function` error

## Previous Behaviour (0.41.2)
Previous version would work. However I used to get change from the value, and there was no wrapping function. But the below added the new node and selected it.
```javascript
  var node = change.value.startBlock;
  var change = this.props.value.change();
  change.replaceNodeByKey(node.key,insertblock).moveToRangeOfNode(insertblock);       
```

Not sure if it makes any difference, but the `insertblock` in my production code comes from the html-parser.

**Comment by ericedem** [comment]
I can repro this with a test case:

```
/** @jsx h */

import h from '../../../helpers/h'

export default function(change) {
  change.replaceNodeByKey('a', { object: 'block', type: 'quote' })
}

export const input = (
  <value>
    <document>
      <paragraph key="a">one</paragraph>
    </document>
  </value>
)

export const output = (
  <value>
    <document>
      <quote />
    </document>
  </value>
)
```

Looks related to: https://github.com/ianstormtaylor/slate/issues/2279

Where removing the only block shouldn't be allowed.

**Comment by ianstormtaylor** [comment]
If the `insertBlock` doesn't have any text nodes this might throw.

One solution would be to change `moveToRangeOfNode`-type commands to act on keys instead of node objects, since in this case the node object is out of date, which is why there is still no text node to select.

**Comment by ianstormtaylor** [comment]
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.
