### PR TITLE
Add missing import

### PR DESCRIPTION
**Pull request by skogsmaskin**
Text was not imported into the node component, breaking things (happened in https://github.com/ianstormtaylor/slate/pull/1064).

``TypeError: Text.isTextList is not a function``

### CODE REVIEW

**Comment by YurkaninRyan** [comment]
Strange the linter didn't catch that for me 🤔

**Comment by AlbertHilb** [comment]
> Strange the linter didn't catch that

It's because `Text` is among browser global variables.

**Comment by YurkaninRyan** [comment]
Brutal!

**Comment by ianstormtaylor** [comment]
Thanks y'all. Browser global overlap is pretty frustrating, but I think it's still worth keeping.
